name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    needs:
      - build
    continue-on-error: ${{ !startsWith(matrix.node-version, 'lts') }}
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - lts/fermium # 14
          - lts/gallium # 16
          - lts/hydrogen # 18
          - current

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - name: Install dependencies
        run: npm clean-install
      - name: Load cached dist
        uses: actions/cache@v3
        id: dist
        with:
          path: dist
          key: ${{ needs.build.outputs.cache-key }}
          fail-on-cache-miss: true
      - run: npm run test

  test-deno:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Load cached dist
        uses: actions/cache@v3
        id: dist
        with:
          path: dist
          key: ${{ needs.build.outputs.cache-key }}
          fail-on-cache-miss: true
      - name: Test Deno Definitions
        run: npm run test-deno -- --no-run
      - name: Test Deno
        run: npm run test-deno -- --no-check
      - run: git reset HEAD --hard

  test-electron:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen # 18
          check-latest: true
          cache: 'npm'
      - name: Install dependencies
        run: npm clean-install
      - name: Load cached dist
        uses: actions/cache@v3
        id: dist
        with:
          path: dist
          key: ${{ needs.build.outputs.cache-key }}
          fail-on-cache-miss: true
      - name: Install Electron
        run: npm install --global xvfb-maybe electron@latest
      - name: Test Electron crypto
        run: xvfb-maybe electron ./test/.electron
      - run: git reset HEAD --hard
